package com.appointunified.enums;
public enum AppointmentStatus { DRAFT, PENDING_DEPOSIT, DEPOSIT_PAID, CONFIRMED, SCHEDULED, IN_QUEUE, IN_MEETING, IN_PROGRESS, COMPLETED, PENDING_BALANCE, PAID_FULL, CANCELLED, NO_SHOW, EXPIRED }
